//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTekrar.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class AltKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AltKategori()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public int AltKategoriId { get; set; }
        public string AltKategoriAdi { get; set; }
        public int KategoriId { get; set; }
        public List<SelectListItem> KategoriList { get; set; }

        public virtual AnaKategori AnaKategori { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}
